### PR TITLE
[REFACTOR] Combining colortemp actions

### PR DESCRIPTION
**Pull request by estilles**
Combining the existing `colortemp` action with the new `colortempk` action (re: #4) as requested by @krocheck.

### CODE REVIEW

**Comment by krocheck** [comment]
So, interestingly, I test 4 values pre dropdown and post.  3 of the 4 properly 'converted' to dropdown values:

- 160 = 6250K
- 200 = 5000K
- 250 = no conversion
- 315 = 3150K

So not sure about the once that didn't convert, but thoughts otherwise @estilles ?

**Comment by estilles** [comment]
> So not sure about the once that didn't convert, but thoughts otherwise @estilles ?

I'll check it out

**Comment by estilles** [comment]
Was able to replicate and found the issue. Submitting another PR to fix.

**Comment by estilles** [comment]
Summited PR #7 to fix

**Pull request merged**
