### PR TITLE
Adding: polling, actions and feedbacks (issue #4)

### PR DESCRIPTION
**Pull request by estilles**
Adding the following contributions, as suggested in issue #4 

Cleanup
- removing unused variables declarations
- Fixing: debug declares/used but not initialized

Features
- polling light for status (power, brightness and temperature)
  - settings to allow enable/disable polling
  - settings to change polling interval
- new actions:
  - Power cycle/toggle on/off
  - Setting temperature in Kelvin (dropdown)
  - Increasing/decreasing temperature
  - increasing/decreasing brightness
- new feedbacks
  - change button color based on power status
  - change button color based on brightness
  - change button color based on temperature

### CODE REVIEW

**Comment by krocheck** [comment]
This all seems fine, but before I update the core my only question is why a color temperature action for Kelvin with a dropdown was added instead of converting the existing action to that mode?  Seems to me the 'RAW' number is not a useful control point for most users anyway.

**Comment by estilles** [comment]
> This all seems fine, but before I update the core my only question is why a color temperature action for Kelvin with a dropdown was added instead of converting the existing action to that mode? Seems to me the 'RAW' number is not a useful control point for most users anyway.

The only reason I added one instead of replacing the existing one was for backwards compatibility. If you prefer to just have one action I'd be more than happy to update my PR.

**Comment by krocheck** [comment]
The underlying value/id is the same though, is it not?  I'd think the values would transpose in a upgrade, but worst case we can do an upgrade script to convert the int to string if the dropdown forces that (I forget if we fixed that or not).

**Comment by estilles** [comment]
> The underlying value/id is the same though, is it not?

Yes. The values are exactly the same. I will refactor and update my PR. Thanks for the comments.

> I'd think the values would transpose in a upgrade, but worst case we can do an upgrade script to convert the int to string if the dropdown forces that (I forget if we fixed that or not).

You're probably right. I don't think there'll be a need for an upgrade script.

**Comment by krocheck** [comment]
This PR was already merged, so I think it will need to be a new one

**Comment by estilles** [comment]
> This PR was already merged, so I think it will need to be a new one

I just realized that. Submitting a new PR shortly.

**Comment by estilles** [comment]
Submitted PR #6

**Pull request merged**
