### PR TITLE
Refactoring: ES6 rewrite

### PR DESCRIPTION
**Pull request by estilles**
Hey guys! 

I noticed a trend within the Companion community/ecosystem towards a migration to ES6. I had some free time on my hands over the holidays, so I decided to take a stab at it.

My PR I intends to accomplish the following:
- **my first attempt at a general ES6 rewrite**
  - separated the code into ES6 modules (`index.js` was getting a bit long)
  - moved everything into an `src` folder, just to keep everything tidy
- **refactored the conversion to kelvin**: A friend who is considerably more knowledgeable in lighting than I am pointed out the color temperature scale used by the Keylight (as well as many other lights) is called "mired". He also told me I don't need that long/ridiculous lookup table (yes, he actually called my code ridiculous), because I could mathematically convert from mired to kelvin (and vice versa). He sent me this [link](https://www.tvtechnology.com/opinions/the-art-of-the-mired-measurement) which explains it very well.
- **added an upgrade script**: Now that I can convert easily between and kelvin, instead of mapping multiple mired values to the corresponding kelvin value rounded up to the nearest 50, I simply used an upgrade script to fix existing mired values. I think this is a better way to handle the issue identified by @krocheck in [this comment](https://github.com/bitfocus/companion-module-elgato-keylight/pull/6#issuecomment-748707836).

Let me know what you guys think.

### CODE REVIEW

**Comment by krocheck** [comment]
@estilles you think its ready?

**Comment by estilles** [comment]
> @estilles you think its ready?

Yes. I've been testing it for the past couple of days and I think I've worked out all the kinks. :-)

**Comment by JTF4** [comment]
@krocheck we could create a new branch and merge the PR with that one if you want testing to continue.

**Comment by krocheck** [comment]
No that's fine, I was seeing the bugfixes coming in here so I wanted to get a sense of where we were at.  I think it looks go, so we can merge this in.

**Pull request merged**
